# Cleaning for plotting
# Getting rid of unnecesseray variables 

datatrees_narrow <- datatrees %>% 
  select(AlterSchätzung, DeutscherN) %>%
  filter(!is.na(DeutscherN)) %>%
  filter(DeutscherN!="unbekannt") %>%
  filter(DeutscherN!="Verschiedene") %>% 
  filter(AlterSchätzung!=0)
  
# Creating new variable we need (Heimisch means domestic)

datatrees_domestic <- datatrees_narrow %>% 
  mutate(Heimisch=case_when(
    DeutscherN=="Ahorn" ~ "Heimisch",
    DeutscherN=="Amberbaum" ~ "Andere",
    DeutscherN=="Amerikanische Linde" ~ "Andere",
    DeutscherN=="Amerikanische Rot-Eiche" ~ "Andere",
    DeutscherN=="Amerikanische Stadt-Linde" ~ "Andere",
    DeutscherN=="Amerikanischer Tulpenbaum" ~ "Andere",
    DeutscherN=="Apfel" ~ "Heimisch",
    DeutscherN=="Atlas-Zeder" ~ "Andere",
    DeutscherN=="Baumhasel" ~ "Andere",
    DeutscherN=="Berg-Ulme" ~ "Heimisch",
    DeutscherN=="Bergahorn" ~ "Heimisch",
    DeutscherN=="Birke" ~ "Heimisch",
    DeutscherN=="Birne" ~ "Heimisch",
    DeutscherN=="Blasenbaum" ~ "Andere",
    DeutscherN=="Blauglockenbaum" ~ "Andere",
    DeutscherN=="Blumen-Esch" ~ "Andere",
    DeutscherN=="Blut-Ahorn, Spitzahorn" ~ "Heimisch",
    DeutscherN=="Blut-Pflaume" ~ "Heimisch",
    DeutscherN=="Chinesische Ulme" ~ "Andere",
    DeutscherN=="Coloradotanne" ~ "Andere",
    DeutscherN=="Crataegus, Dorn" ~ "Heimisch",
    DeutscherN=="Dreidorniger Lederhülsenbaum, Gleditschie" ~ "Andere",
    DeutscherN=="Eberesche, Mehlbeere, Vogelbeerbaum" ~ "Heimisch",
    DeutscherN=="Echter Korkbaum, Amur-Korkbaum" ~ "Andere",
    DeutscherN=="Echter Rotdorn" ~ "Heimisch",
    DeutscherN=="Eibe" ~ "Heimisch",
    DeutscherN=="Eiche" ~ "Heimisch",
    DeutscherN=="Einblättrige Esche" ~ "Andere",
    DeutscherN=="Eisenbaum" ~ "Andere",
    DeutscherN=="Eisenholzbaum" ~ "Andere",
    DeutscherN=="Erle" ~ "Heimisch",
    DeutscherN=="Esche" ~ "Heimisch",
    DeutscherN=="Eschen-Ahorn" ~ "Andere",
    DeutscherN=="Etagen Hartriegel" ~ "Andere",
    DeutscherN=="Fächer-Ahorn" ~ "Andere",
    DeutscherN=="Farn- oder geschlitzblättrige Birke" ~ "Andere",
    DeutscherN=="Feldahorn" ~ "Heimisch",
    DeutscherN=="Felsenbirne" ~ "Heimisch",
    DeutscherN=="Feuerahorn" ~ "Andere",
    DeutscherN=="Fichte" ~ "Heimisch",
    DeutscherN=="Flügelnuß" ~ "Heimisch",
    DeutscherN=="Gelbe Gleditschie" ~ "Andere",
    DeutscherN=="Gemeine Esche" ~ "Heimisch",
    DeutscherN=="Gemeiner Goldregen" ~ "Andere",
    DeutscherN=="Gemeiner Judasbaum, Herzbaum" ~ "Andere",
    DeutscherN=="Gewöhnliche Eberesche" ~ "Heimisch",
    DeutscherN=="Gewöhnliche Kiefer" ~ "Heimisch",
    DeutscherN=="Ginkgo" ~ "Andere",
    DeutscherN=="Ginkgobaum, Fächerblattbaum" ~ "Andere",
    DeutscherN=="Gleditsie, Lederhülsenbaum" ~ "Andere",
    DeutscherN=="Goldrobinie" ~ "Andere",
    DeutscherN=="Götterbaum" ~ "Andere",
    DeutscherN=="Großblättrige Sommerlinde" ~ "Heimisch",
    DeutscherN=="Grüne Hängebuche" ~ "Heimisch",
    DeutscherN=="Hainbuche, Weißbuche" ~ "Heimisch",
    DeutscherN=="Hasel" ~ "Heimisch",
    DeutscherN=="Holzbirne, Gemeine Birne" ~ "Heimisch",
    DeutscherN=="Hopfenbuche" ~ "Andere",
    DeutscherN=="Italienische Erle" ~ "Andere",
    DeutscherN=="Japanische Nelken-Kirsche" ~ "Andere",
    DeutscherN=="Japanischer Schnurbaum" ~ "Andere",
    DeutscherN=="Judasblattbaum, Lebkuchenbaum" ~ "Andere",
    DeutscherN=="Kaiserlinde" ~ "Heimisch",
    DeutscherN=="Kanadische Hemlocktanne" ~ "Andere",
    DeutscherN=="Kanadische Holz-Pappel" ~ "Andere",
    DeutscherN=="Kastanie" ~ "Heimisch",
    DeutscherN=="Kegel-Robinie" ~ "Andere",
    DeutscherN=="Kiefer" ~ "Heimisch",
    DeutscherN=="Kirsche" ~ "Heimisch",
    DeutscherN=="Kolchischer Ahorn" ~ "Andere",
    DeutscherN=="Krimlinde" ~ "Heimisch",
    DeutscherN=="Kugel-Trompetenbaum" ~ "Andere",
    DeutscherN=="Kugelahorn" ~ "Heimisch",
    DeutscherN=="Kugelrobinie" ~ "Andere",
    DeutscherN=="Kupfer-Felsenbirne" ~ "Andere",
    DeutscherN=="Küstenmammutbaum" ~ "Andere",
    DeutscherN=="Lebensbaum" ~ "Andere",
    DeutscherN=="Lederblättriger Weißdorn" ~ "Andere",
    DeutscherN=="Libanon-Zeder" ~ "Andere",
    DeutscherN=="Linde" ~ "Heimisch",
    DeutscherN=="Lorbeermispel, Glanzmispel" ~ "Andere",
    DeutscherN=="Magnolie" ~ "Andere",
    DeutscherN=="Mammutbaum" ~ "Andere",
    DeutscherN=="Marone, Eßkastanie" ~ "Andere",
    DeutscherN=="Mehlbeere" ~ "Heimisch",
    DeutscherN=="Österreichische Schwarzkiefer" ~ "Andere",
    DeutscherN=="Papierbirke" ~ "Andere",
    DeutscherN=="Pappel" ~ "Heimisch",
    DeutscherN=="Pfaffenhütchen (Spindelbaum" ~ "Heimisch",
    DeutscherN=="Platane" ~ "Heimisch",
    DeutscherN=="Purpur-Kastanie, Blut-Kastanie" ~ "Heimisch",
    DeutscherN=="Pyramiden-Eiche, Säulen-Eiche" ~ "Heimisch",
    DeutscherN=="Pyramiden-Hainbuche" ~ "Heimisch",
    DeutscherN=="Roßkastanie" ~ "Heimisch",
    DeutscherN=="Rot-Buche" ~ "Heimisch",
    DeutscherN=="Rotahorn" ~ "Andere",
    DeutscherN=="Roter Holunder" ~ "Heimisch",
    DeutscherN=="Rundblättrige Rotbuche" ~ "Heimisch",
    DeutscherN=="Sal-Weide" ~ "Heimisch",
    DeutscherN=="Sandbirke" ~ "Heimisch",
    DeutscherN=="Sanddorn" ~ "Heimisch",
    DeutscherN=="Säulen-Tulpenbaum" ~ "Andere",
    DeutscherN=="Säulen-Ulme" ~ "Heimisch",
    DeutscherN=="Säulenpappel, Pyramidenpappel" ~ "Heimisch",
    DeutscherN=="Säulenrobinie" ~ "Andere",
    DeutscherN=="Scheinakazie" ~ "Andere",
    DeutscherN=="Scheinzypresse" ~ "Andere",
    DeutscherN=="Schmalkroniger Rotahorn" ~ "Andere",
    DeutscherN=="Schnurbaum" ~ "Andere",
    DeutscherN=="Schwarz-Erle, Rot-Erle" ~ "Heimisch",
    DeutscherN=="Schwarzer Holunder" ~ "Heimisch",
    DeutscherN=="Schwarzkiefer" ~ "Andere",
    DeutscherN=="Schwarznuß" ~ "Andere",
    DeutscherN=="Schwarzpappel" ~ "Heimisch",
    DeutscherN=="Schwedische Mehlbeere" ~ "Andere",
    DeutscherN=="Silber-Ahorn" ~ "Andere",
    DeutscherN=="Silber-Weide" ~ "Heimisch",
    DeutscherN=="Silberlinde" ~ "Andere",
    DeutscherN=="Silberpappel" ~ "Heimisch",
    DeutscherN=="Sommer-Eiche, Stieleiche" ~ "Heimisch",
    DeutscherN=="Späte Traubenkirsche" ~ "Andere",
    DeutscherN=="Späth's Erle" ~ "Heimisch",
    DeutscherN=="Spitzahorn" ~ "Heimisch",
    DeutscherN=="Spitzahorn Cleveland" ~ "Andere",
    DeutscherN=="Stechpalme" ~ "Heimisch",
    DeutscherN=="Straßen-Akazie" ~ "Andere",
    DeutscherN=="Sumpf-Eiche" ~ "Andere",
    DeutscherN=="Tanne" ~ "Heimisch",
    DeutscherN=="Trauben-Kirsche" ~ "Heimisch",
    DeutscherN=="Trompetenbaum" ~ "Andere",
    DeutscherN=="Tulpenbaum" ~ "Andere",
    DeutscherN=="Ulme, Rüster" ~ "Heimisch",
    DeutscherN=="Ungarische Eiche" ~ "Andere",
    DeutscherN=="Ungarische Silberlinde" ~ "Andere",
    DeutscherN=="Urweltmammutbaum, Chinesisches Rotholz" ~ "Andere",
    DeutscherN=="Wacholder" ~ "Heimisch",
    DeutscherN=="Wal-, Nußbaum" ~ "Heimisch",
    DeutscherN=="Walnuß" ~ "Heimisch",
    DeutscherN=="Weide" ~ "Heimisch",
    DeutscherN=="Weißdorn" ~ "Heimisch",
    DeutscherN=="Winter-Eiche, Trauben-Eiche" ~ "Heimisch",
    DeutscherN=="Winterlinde" ~ "Heimisch",
    DeutscherN=="Winterlinde Cordaley" ~ "Heimisch",
    DeutscherN=="Winterlinde Dila" ~ "Heimisch",
    DeutscherN=="Zeder" ~ "Andere",
    DeutscherN=="Zelkove" ~ "Andere",
    DeutscherN=="Zier-Birne" ~ "Heimisch",
    DeutscherN=="Zierapfel" ~ "Heimisch",
    DeutscherN=="Zierkirsche 'Spire'" ~ "Heimisch"
  )) %>% 
  filter(!is.na(Heimisch))

# Save this

write_csv(datatrees_domestic, "output_data/datatrees_domestic.csv")

#Cleaning for mapping
#Getting rid of unnecessary variables

trees_small <- trees %>%
  select(AlterSchae, DeutscherN, geometry) %>%
  filter(!is.na(DeutscherN)) %>%
  filter(DeutscherN!="unbekannt") %>%
  filter(DeutscherN!="Verschiedene") %>% 
  filter(AlterSchae!=0)

#Creating new variable we need (Heimisch means domestic)

trees_domestic <- trees_small %>% 
  mutate(Heimisch=case_when(
    DeutscherN=="Ahorn" ~ "Heimisch",
    DeutscherN=="Amberbaum" ~ "Andere",
    DeutscherN=="Amerikanische Linde" ~ "Andere",
    DeutscherN=="Amerikanische Rot-Eiche" ~ "Andere",
    DeutscherN=="Amerikanische Stadt-Linde" ~ "Andere",
    DeutscherN=="Amerikanischer Tulpenbaum" ~ "Andere",
    DeutscherN=="Apfel" ~ "Heimisch",
    DeutscherN=="Atlas-Zeder" ~ "Andere",
    DeutscherN=="Baumhasel" ~ "Andere",
    DeutscherN=="Berg-Ulme" ~ "Heimisch",
    DeutscherN=="Bergahorn" ~ "Heimisch",
    DeutscherN=="Birke" ~ "Heimisch",
    DeutscherN=="Birne" ~ "Heimisch",
    DeutscherN=="Blasenbaum" ~ "Andere",
    DeutscherN=="Blauglockenbaum" ~ "Andere",
    DeutscherN=="Blumen-Esch" ~ "Andere",
    DeutscherN=="Blut-Ahorn, Spitzahorn" ~ "Heimisch",
    DeutscherN=="Blut-Pflaume" ~ "Heimisch",
    DeutscherN=="Chinesische Ulme" ~ "Andere",
    DeutscherN=="Coloradotanne" ~ "Andere",
    DeutscherN=="Crataegus, Dorn" ~ "Heimisch",
    DeutscherN=="Dreidorniger Lederhülsenbaum, Gleditschie" ~ "Andere",
    DeutscherN=="Eberesche, Mehlbeere, Vogelbeerbaum" ~ "Heimisch",
    DeutscherN=="Echter Korkbaum, Amur-Korkbaum" ~ "Andere",
    DeutscherN=="Echter Rotdorn" ~ "Heimisch",
    DeutscherN=="Eibe" ~ "Heimisch",
    DeutscherN=="Eiche" ~ "Heimisch",
    DeutscherN=="Einblättrige Esche" ~ "Andere",
    DeutscherN=="Eisenbaum" ~ "Andere",
    DeutscherN=="Eisenholzbaum" ~ "Andere",
    DeutscherN=="Erle" ~ "Heimisch",
    DeutscherN=="Esche" ~ "Heimisch",
    DeutscherN=="Eschen-Ahorn" ~ "Andere",
    DeutscherN=="Etagen Hartriegel" ~ "Andere",
    DeutscherN=="Fächer-Ahorn" ~ "Andere",
    DeutscherN=="Farn- oder geschlitzblättrige Birke" ~ "Andere",
    DeutscherN=="Feldahorn" ~ "Heimisch",
    DeutscherN=="Felsenbirne" ~ "Heimisch",
    DeutscherN=="Feuerahorn" ~ "Andere",
    DeutscherN=="Fichte" ~ "Heimisch",
    DeutscherN=="Flügelnuß" ~ "Heimisch",
    DeutscherN=="Gelbe Gleditschie" ~ "Andere",
    DeutscherN=="Gemeine Esche" ~ "Heimisch",
    DeutscherN=="Gemeiner Goldregen" ~ "Andere",
    DeutscherN=="Gemeiner Judasbaum, Herzbaum" ~ "Andere",
    DeutscherN=="Gewöhnliche Eberesche" ~ "Heimisch",
    DeutscherN=="Gewöhnliche Kiefer" ~ "Heimisch",
    DeutscherN=="Ginkgo" ~ "Andere",
    DeutscherN=="Ginkgobaum, Fächerblattbaum" ~ "Andere",
    DeutscherN=="Gleditsie, Lederhülsenbaum" ~ "Andere",
    DeutscherN=="Goldrobinie" ~ "Andere",
    DeutscherN=="Götterbaum" ~ "Andere",
    DeutscherN=="Großblättrige Sommerlinde" ~ "Heimisch",
    DeutscherN=="Grüne Hängebuche" ~ "Heimisch",
    DeutscherN=="Hainbuche, Weißbuche" ~ "Heimisch",
    DeutscherN=="Hasel" ~ "Heimisch",
    DeutscherN=="Holzbirne, Gemeine Birne" ~ "Heimisch",
    DeutscherN=="Hopfenbuche" ~ "Andere",
    DeutscherN=="Italienische Erle" ~ "Andere",
    DeutscherN=="Japanische Nelken-Kirsche" ~ "Andere",
    DeutscherN=="Japanischer Schnurbaum" ~ "Andere",
    DeutscherN=="Judasblattbaum, Lebkuchenbaum" ~ "Andere",
    DeutscherN=="Kaiserlinde" ~ "Heimisch",
    DeutscherN=="Kanadische Hemlocktanne" ~ "Andere",
    DeutscherN=="Kanadische Holz-Pappel" ~ "Andere",
    DeutscherN=="Kastanie" ~ "Heimisch",
    DeutscherN=="Kegel-Robinie" ~ "Andere",
    DeutscherN=="Kiefer" ~ "Heimisch",
    DeutscherN=="Kirsche" ~ "Heimisch",
    DeutscherN=="Kolchischer Ahorn" ~ "Andere",
    DeutscherN=="Krimlinde" ~ "Heimisch",
    DeutscherN=="Kugel-Trompetenbaum" ~ "Andere",
    DeutscherN=="Kugelahorn" ~ "Heimisch",
    DeutscherN=="Kugelrobinie" ~ "Andere",
    DeutscherN=="Kupfer-Felsenbirne" ~ "Andere",
    DeutscherN=="Küstenmammutbaum" ~ "Andere",
    DeutscherN=="Lebensbaum" ~ "Andere",
    DeutscherN=="Lederblättriger Weißdorn" ~ "Andere",
    DeutscherN=="Libanon-Zeder" ~ "Andere",
    DeutscherN=="Linde" ~ "Heimisch",
    DeutscherN=="Lorbeermispel, Glanzmispel" ~ "Andere",
    DeutscherN=="Magnolie" ~ "Andere",
    DeutscherN=="Mammutbaum" ~ "Andere",
    DeutscherN=="Marone, Eßkastanie" ~ "Andere",
    DeutscherN=="Mehlbeere" ~ "Heimisch",
    DeutscherN=="Österreichische Schwarzkiefer" ~ "Andere",
    DeutscherN=="Papierbirke" ~ "Andere",
    DeutscherN=="Pappel" ~ "Heimisch",
    DeutscherN=="Pfaffenhütchen (Spindelbaum" ~ "Heimisch",
    DeutscherN=="Platane" ~ "Heimisch",
    DeutscherN=="Purpur-Kastanie, Blut-Kastanie" ~ "Heimisch",
    DeutscherN=="Pyramiden-Eiche, Säulen-Eiche" ~ "Heimisch",
    DeutscherN=="Pyramiden-Hainbuche" ~ "Heimisch",
    DeutscherN=="Roßkastanie" ~ "Heimisch",
    DeutscherN=="Rot-Buche" ~ "Heimisch",
    DeutscherN=="Rotahorn" ~ "Andere",
    DeutscherN=="Roter Holunder" ~ "Heimisch",
    DeutscherN=="Rundblättrige Rotbuche" ~ "Heimisch",
    DeutscherN=="Sal-Weide" ~ "Heimisch",
    DeutscherN=="Sandbirke" ~ "Heimisch",
    DeutscherN=="Sanddorn" ~ "Heimisch",
    DeutscherN=="Säulen-Tulpenbaum" ~ "Andere",
    DeutscherN=="Säulen-Ulme" ~ "Heimisch",
    DeutscherN=="Säulenpappel, Pyramidenpappel" ~ "Heimisch",
    DeutscherN=="Säulenrobinie" ~ "Andere",
    DeutscherN=="Scheinakazie" ~ "Andere",
    DeutscherN=="Scheinzypresse" ~ "Andere",
    DeutscherN=="Schmalkroniger Rotahorn" ~ "Andere",
    DeutscherN=="Schnurbaum" ~ "Andere",
    DeutscherN=="Schwarz-Erle, Rot-Erle" ~ "Heimisch",
    DeutscherN=="Schwarzer Holunder" ~ "Heimisch",
    DeutscherN=="Schwarzkiefer" ~ "Andere",
    DeutscherN=="Schwarznuß" ~ "Andere",
    DeutscherN=="Schwarzpappel" ~ "Heimisch",
    DeutscherN=="Schwedische Mehlbeere" ~ "Andere",
    DeutscherN=="Silber-Ahorn" ~ "Andere",
    DeutscherN=="Silber-Weide" ~ "Heimisch",
    DeutscherN=="Silberlinde" ~ "Andere",
    DeutscherN=="Silberpappel" ~ "Heimisch",
    DeutscherN=="Sommer-Eiche, Stieleiche" ~ "Heimisch",
    DeutscherN=="Späte Traubenkirsche" ~ "Andere",
    DeutscherN=="Späth's Erle" ~ "Heimisch",
    DeutscherN=="Spitzahorn" ~ "Heimisch",
    DeutscherN=="Spitzahorn Cleveland" ~ "Andere",
    DeutscherN=="Stechpalme" ~ "Heimisch",
    DeutscherN=="Straßen-Akazie" ~ "Andere",
    DeutscherN=="Sumpf-Eiche" ~ "Andere",
    DeutscherN=="Tanne" ~ "Heimisch",
    DeutscherN=="Trauben-Kirsche" ~ "Heimisch",
    DeutscherN=="Trompetenbaum" ~ "Andere",
    DeutscherN=="Tulpenbaum" ~ "Andere",
    DeutscherN=="Ulme, Rüster" ~ "Heimisch",
    DeutscherN=="Ungarische Eiche" ~ "Andere",
    DeutscherN=="Ungarische Silberlinde" ~ "Andere",
    DeutscherN=="Urweltmammutbaum, Chinesisches Rotholz" ~ "Andere",
    DeutscherN=="Wacholder" ~ "Heimisch",
    DeutscherN=="Wal-, Nußbaum" ~ "Heimisch",
    DeutscherN=="Walnuß" ~ "Heimisch",
    DeutscherN=="Weide" ~ "Heimisch",
    DeutscherN=="Weißdorn" ~ "Heimisch",
    DeutscherN=="Winter-Eiche, Trauben-Eiche" ~ "Heimisch",
    DeutscherN=="Winterlinde" ~ "Heimisch",
    DeutscherN=="Winterlinde Cordaley" ~ "Heimisch",
    DeutscherN=="Winterlinde Dila" ~ "Heimisch",
    DeutscherN=="Zeder" ~ "Andere",
    DeutscherN=="Zelkove" ~ "Andere",
    DeutscherN=="Zier-Birne" ~ "Heimisch",
    DeutscherN=="Zierapfel" ~ "Heimisch",
    DeutscherN=="Zierkirsche 'Spire'" ~ "Heimisch"
  )) %>% 
  filter(!is.na(Heimisch))

# Joining

trees_joined <- trees_domestic %>%
  st_transform(crs=st_crs(cologne))
cologne_trees <- st_join(cologne, trees_joined, left=T)